export const EDITANDOCONCHA = 'EDITANDOCONCHA';
export const NOEDITANDOCONCHA = 'NOEDITANDOCONCHA';
export const NUEVACONCHA = 'NUEVACONCHA';
export const ELIMINACONCHA = 'ELIMINACONCHA';
export const SUMAMEJILLON = 'SUMAMEJILLON';
export const RESTAMEJILLON = 'RESTAMEJILLON';
export const NUEVORESULTADO = 'NUEVORESULTADO';
export const NUEVODIA = 'NUEVODIA';